use serde::{Deserialize, Serialize};

use crate::changelog::preset::Preset;
use crate::changelog::rule::Rule;

/// Configuration for the changelog generator.
///
/// Defines the configuration options for the changelog generator.
/// It allows specifying a preset of rules or custom rules for categorizing commit messages
/// and a template for generating the changelog.
///
/// # Default
/// By default, the configuration uses the `ConventionalCommits` preset, no custom rules,
/// and a standard Markdown template.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChangelogGeneratorConfig {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preset: Option<Preset>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<Rule>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub header_template: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body_template: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footer_template: Option<String>,
}

impl Default for ChangelogGeneratorConfig {
    fn default() -> Self {
        ChangelogGeneratorConfig {
            preset: Some(Preset::ConventionalCommits),
            rules: None,
            header_template: Some("## Changelog\n\nAll notable changes to this project will be documented in this file.".to_string()),
            body_template: Some("### [{{version}}] - {{date}}\n\n{{changes}}".to_string()),
            footer_template: Some("Generated by changelog-generator".to_string()),
        }
    }
}
